global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rag-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - gbragfastapi-accyhah2evcnfxev.westeurope-01.azurewebsites.net
          #- host.docker.internal:8000
